name: prescription
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pdf: ^3.11.1
  path_provider: ^2.1.5
  printing: ^5.13.4
  html_editor_enhanced: ^2.6.0
  flutter_dropdown_alert: ^1.0.7
  html_to_pdf: ^0.8.1
  pdf_render: ^1.4.12
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  package_info_plus: ^8.1.1
  flutter_pdfview: ^1.3.4
  flutter_widget_from_html: ^0.15.3
  downloadsfolder: ^1.1.0
  media_scanner:
    git:
      url: https://github.com/wukgdu/media_scanner.git
      ref: efe757c

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 700

    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 700

    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 300
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 700


